### ISSUE TITLE
Too many dependencies

### ISSUE THREAD

**Issue by david-bouyssie** [koendeschacht/count-db#1]
Your project has a nice API and comes with nice features but the main problem is the high number of required dependencies: Spring Framework, Guava, jackson, jetty....

I think it's to heavy weight for the purpose of this project.

**Comment by koendeschacht** [comment]
Hi David,

Thanks for the comment. I know that currently the project has quite a number of dependencies. Some are pretty hard-wired to the project (spring, jackson) but other might indeed be removed. May I ask whether you have tried using count-db, or for what type of project you would consider using it?

Regards,
Koen

**Comment by david-bouyssie** [comment]
I have a project where I create remote jobs on server. This servers process JSON-RPC requests and returns results asynchronously. I have to persist the status of jobs running on the server and to increment the ID of each new job.
I was considering count-db for this task but I don't want to have the Spring framework dependency, nor the jetty one.
I need something quite simple so I think I will use isntead an SQLite file with an auto-incremented field.
Keep up the good work !
